#

pluginName = PLA Model Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Actor_type = Actor
_UI_ThirdParty_type = Third Party
_UI_DataStorage_type = Data Storage
_UI_PersonalDataAsset_type = Personal Data Asset
_UI_Purpose_type = Purpose
_UI_PLAs_type = PL As
_UI_Identifiable_type = Identifiable
_UI_PLA_type = PLA
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Actor_name_feature = Name
_UI_Actor_contact_feature = Contact
_UI_Actor_address_feature = Address
_UI_PersonalDataAsset_name_feature = Name
_UI_PersonalDataAsset_type_feature = Type
_UI_PersonalDataAsset_privacyLabel_feature = Privacy Label
_UI_PersonalDataAsset_legalBasis_feature = Legal Basis
_UI_Purpose_name_feature = Name
_UI_Purpose_purposeText_feature = Purpose Text
_UI_Purpose_actions_feature = Actions
_UI_Purpose_incomeAssets_feature = Income Assets
_UI_Purpose_outcomeAssets_feature = Outcome Assets
_UI_PLAs_actors_feature = Actors
_UI_PLAs_purposes_feature = Purposes
_UI_PLAs_personalDataAssets_feature = Personal Data Assets
_UI_Identifiable_ID_feature = ID
_UI_Identifiable_number_feature = Number
_UI_PLA_plas_feature = Plas
_UI_Unknown_feature = Unspecified

_UI_LegalBasis_Consent_literal = Consent
_UI_LegalBasis_Contract_literal = Contract
_UI_LegalBasis_LegalObligation_literal = LegalObligation
_UI_LegalBasis_LegitimateInterest_literal = LegitimateInterest
_UI_LegalBasis_VitalInterest_literal = VitalInterest
_UI_LegalBasis_PublicTask_literal = PublicTask
