<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.secdfd.org/secdfd" nsPrefix="org.secdfd">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.secdfd"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="H"/>
    <eLiterals name="M" value="1"/>
    <eLiterals name="L" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="#//NamedEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" lowerBound="1"
        upperBound="-1" eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//AssetType"
        defaultValueLiteral="String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibility" upperBound="-1"
        eType="#//Responsibility" containment="true" eOpposite="#//Responsibility/process"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Channel">
    <eLiterals name="WiFi"/>
    <eLiterals name="VLAN" value="2"/>
    <eLiterals name="ETH" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDFD" eSuperTypes="#//NamedEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" upperBound="-1"
        eType="#//Asset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trustzones" upperBound="-1"
        eType="#//TrustZone" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResponsibilityType">
    <eLiterals name="Store" value="1"/>
    <eLiterals name="Comparator" value="2"/>
    <eLiterals name="Discarder" value="3"/>
    <eLiterals name="Joiner" value="4"/>
    <eLiterals name="Copier" value="5"/>
    <eLiterals name="Splitter" value="6"/>
    <eLiterals name="Forward" value="7"/>
    <eLiterals name="EncryptOrHash" value="8"/>
    <eLiterals name="Decrypt" value="9"/>
    <eLiterals name="Authenticator" value="10"/>
    <eLiterals name="Authoriser" value="11"/>
    <eLiterals name="Verifier" value="12"/>
    <eLiterals name="User" value="13"/>
    <eLiterals name="ML" value="14"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStore" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Channel" eType="#//Channel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalEntity" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Objective">
    <eLiterals name="Integrity"/>
    <eLiterals name="Confidentiality" value="1"/>
    <eLiterals name="Availability" value="2"/>
    <eLiterals name="Accountability" value="3"/>
    <eLiterals name="Privacy" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true" eSuperTypes="#//NamedEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outflows" upperBound="-1"
        eType="#//Flow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assumption" upperBound="-1"
        eType="#//Assumption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assets" upperBound="-1"
        eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inflows" upperBound="-1"
        eType="#//Flow"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Attacker" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedEntity" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Layer">
    <eLiterals name="Transport"/>
    <eLiterals name="Architectural" value="1"/>
    <eLiterals name="Application" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="constraint_1"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="constraint_1" value="Tuple {&#xA;&#x9;message : String = 'Privacy as objective can only have a high or low priority.',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;self.Objective = Objective::Privacy implies (self.Priority = Priority::H or self.Priority = Priority::L)&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Objective" eType="#//Objective"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Priority" eType="#//Priority"
        defaultValueLiteral="H"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assumption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Objective" upperBound="-1"
        eType="#//Objective"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Layer" eType="#//Layer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttackerProfile" eSuperTypes="#//NamedEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Observation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrustZone" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subzones" upperBound="-1"
        eType="#//TrustZone" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attackerprofile" upperBound="-1"
        eType="#//AttackerProfile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Responsibility" eSuperTypes="#//NamedEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Action" upperBound="-1"
        eType="#//ResponsibilityType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomeassets" upperBound="-1"
        eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outcomeassets" upperBound="-1"
        eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" eType="#//Process"
        eOpposite="#//Process/responsibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssetType">
    <eLiterals name="String" literal="String"/>
    <eLiterals name="Object" value="1" literal="Object"/>
    <eLiterals name="Number" value="2" literal="Number"/>
    <eLiterals name="Vector" value="3" literal="Vector"/>
    <eLiterals name="Boolean" value="4" literal="Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MLResponsibilityType">
    <eLiterals name="Classification"/>
    <eLiterals name="DecisionMaking" value="1" literal="Decision-Making"/>
    <eLiterals name="Regression" value="2"/>
    <eLiterals name="Clustering" value="3"/>
    <eLiterals name="AnomalyDetection" value="4"/>
    <eLiterals name="NaturalLanguageProcessing" value="5" literal="Natural-Language-Processing"/>
    <eLiterals name="ComputerVision" value="6" literal="Computer-Vision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLResponsibility" eSuperTypes="#//Responsibility">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="constraint_ml_responsibility"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="constraint_ml_responsibility" value="Tuple {&#xA;&#x9;message : String = 'MLResponsibility can only be used when ML is selected as a ResponsibilityType in Action.',&#xA;&#x9;status : Boolean = &#xA;&#x9;&#x9;&#x9;self.Action->includes(ResponsibilityType::ML)&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mlAction" upperBound="-1"
        eType="#//MLResponsibilityType"/>
  </eClassifiers>
</ecore:EPackage>
