/**
 *
 * $Id$
 */
package org.secdfd.model.validation;

import org.eclipse.emf.common.util.EList;

import org.secdfd.model.AssetType;
import org.secdfd.model.Element;
import org.secdfd.model.Value;

/**
 * A sample validator interface for {@link org.secdfd.model.Asset}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssetValidator {
	boolean validate();

	boolean validateValue(EList<Value> value);
	boolean validateSource(Element value);
	boolean validateTargets(EList<Element> value);
	boolean validateType(AssetType value);
}
