/**
 *
 * $Id$
 */
package org.secdfd.model.validation;

import org.eclipse.emf.common.util.EList;

import org.secdfd.model.Layer;
import org.secdfd.model.Objective;

/**
 * A sample validator interface for {@link org.secdfd.model.Assumption}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssumptionValidator {
	boolean validate();

	boolean validateObjective(EList<Objective> value);
	boolean validateLayer(Layer value);
}
