/**
 *
 * $Id$
 */
package org.secdfd.model.validation;

import org.eclipse.emf.common.util.EList;

import org.secdfd.model.Asset;
import org.secdfd.model.ContractType;

/**
 * A sample validator interface for {@link org.secdfd.model.ContractBase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContractBaseValidator {
	boolean validate();

	boolean validateIncomeassets(EList<Asset> value);
	boolean validateOutcomeassets(EList<Asset> value);
	boolean validateProcess(org.secdfd.model.Process value);
	boolean validateTask(EList<ContractType> value);
}
