/**
 *
 * $Id$
 */
package org.secdfd.model.validation;

import org.eclipse.emf.common.util.EList;

import org.secdfd.model.Asset;
import org.secdfd.model.Element;
import org.secdfd.model.TrustZone;

/**
 * A sample validator interface for {@link org.secdfd.model.EDFD}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EDFDValidator {
	boolean validate();

	boolean validateAsset(EList<Asset> value);
	boolean validateTrustzones(EList<TrustZone> value);
	boolean validateElements(EList<Element> value);
}
