/**
 *
 * $Id$
 */
package org.secdfd.model.validation;

import org.eclipse.emf.common.util.EList;

import org.secdfd.model.Asset;
import org.secdfd.model.Assumption;
import org.secdfd.model.Flow;

/**
 * A sample validator interface for {@link org.secdfd.model.Element}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementValidator {
	boolean validate();

	boolean validateOutflows(EList<Flow> value);
	boolean validateAssumption(EList<Assumption> value);
	boolean validateAssets(EList<Asset> value);
	boolean validateInflows(EList<Flow> value);
	boolean validateAttacker(boolean value);
}
