/**
 *
 * $Id$
 */
package org.secdfd.model.validation;

import org.secdfd.model.Level;
import org.secdfd.model.Objective;

/**
 * A sample validator interface for {@link org.secdfd.model.Value}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValueValidator {
	boolean validate();

	boolean validateObjective(Objective value);
	boolean validateLevel(Level value);
}
